apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: default
  name: dexes-apps-ingress
  annotations:
    kubernetes.io/ingress-class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production-issuer
    "nginx.ingress.kubernetes.io/proxy-body-size": 100m
spec:
  tls:
    - hosts:
        - dexpods.eu
        - '*.dexpods.eu'
        - '*.staging.dexpods.eu'
      secretName: letsencrypt-production-tls2
  rules:
    - host: staging.dexpods.eu
      http:
        paths:
          - path: /link-lib/bulk
            backend:
              serviceName: cache-staging
              servicePort: 3030
    - host: '*.staging.dexpods.eu'
      http:
        paths:
          - path: /link-lib/bulk
            backend:
              serviceName: cache-staging
              servicePort: 3030
    - host: staging.dexpods.eu
      http:
        paths:
          - path: /
            backend:
              serviceName: dexes-staging
              servicePort: 80
    - host: '*.staging.dexpods.eu'
      http:
        paths:
          - path: /
            backend:
              serviceName: dexes-staging
              servicePort: 80
    - host: dexpods.eu
      http:
        paths:
          - path: /link-lib/bulk
            backend:
              serviceName: cache-production
              servicePort: 3030
    - host: '*.dexpods.eu'
      http:
        paths:
          - path: /link-lib/bulk
            backend:
              serviceName: cache-production
              servicePort: 3030
    - host: dexpods.eu
      http:
        paths:
          - path: /
            backend:
              serviceName: dexes-production
              servicePort: 80
    - host: '*.dexpods.eu'
      http:
        paths:
          - path: /
            backend:
              serviceName: dexes-production
              servicePort: 80
