require:
  - rubocop-rails
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Metrics/BlockLength:
  ExcludedMethods:
    - before
    - configure
    - context
    - define
    - describe
    - draw
    - factory
    - feature
    - has_one
    - included
    - it
    - let
    - namespace
    - scenario
    - shared_examples
    - shared_examples_for
    - test
    - setup
Layout/LineLength:
  Max: 120
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
Style/Documentation:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/RaiseArgs:
  EnforcedStyle: compact
