apiVersion: apps/v1
kind: Deployment
metadata:
  name: cache
  namespace: staging
spec:
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
        - name: cache
          image: registry.gitlab.com/ontola/cache/master:staging
          envFrom:
            - secretRef:
                name: cache-secret
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              memory: 200Mi
              cpu: 250m
      imagePullSecrets:
        - name: gitlab-cache
