apiVersion: v1
kind: Service
metadata:
  name: dexes-frontend
  namespace: staging
spec:
  type: ClusterIP
  selector:
    app: dexes-frontend
  ports:
    - name: "http"
      port: 80
      targetPort: 8080
