default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: <%= ENV['DEXES_DATABASE'] %>
  username: <%= ENV['POSTGRESQL_USERNAME'] %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  port: <%= ENV['POSTGRESQL_PORT'] %>
  schema_search_path: 'public,shared_extensions'
development:
  <<: *default
test:
  <<: *default
  database: dexpod_test_local
production: &production
  <<: *default
staging:
  <<: *production
