test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

digitalocean:
  service: S3
  endpoint: <%= ENV['STORAGE_ENDPOINT'] %>
  access_key_id: <%= ENV['STORAGE_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['STORAGE_SECRET'] %>
  bucket: <%= ENV['STORAGE_BUCKET'] %>
  region: unused
